### PR TITLE
WIP: Move string handling code to new file

### PR DESCRIPTION
**Pull request by lysnikolaou**

### CODE REVIEW

**Comment by lysnikolaou** [comment]
Note that this somehow compiles with clang but not gcc on my machine.

**Comment by gvanrossum** [comment]
Huh, on my Mac, gcc is an alias for clang. Wild guess: maybe "strings.h" is a common filename and renaming it to something else might help?

**Comment by gvanrossum** [comment]
Also, what errors do you get? That might give me a clue.

**Comment by lysnikolaou** [comment]
Around 18000 lines of error messages with many error types. `gcc` compains for probably every file included in Python.h. The most common error message is something like `expected declaration specifiers or ‘...’ before PyObject`.

**Comment by lysnikolaou** [comment]
> Wild guess: maybe "strings.h" is a common filename and renaming it to something else might help?

That was actually it! Thanks a lot!

**Comment by lysnikolaou** [comment]
I renamed both files to `parse_string.[ch]`. Can you think of something better that this?

**Comment by gvanrossum** [comment]
Excellent, those filenames are fine.

**Pull request closed without merging**
