### PR TITLE
Add pytest-benchmark plugin and benchmark test_ast_generation

### PR DESCRIPTION
**Pull request by lysnikolaou**
Benchmarking is disabled by default, so that it does not run on Travis as it significantly slows down testing. We can then enable it by using `pytest --benchmark-enable test/test_ast_generation`.

### CODE REVIEW

**Comment by pablogsal** [comment]
Very nice!

Inpecting the results on my machine show that there is a big deviation between the max and the mean/average:
```
---------------------------------------------------------------------------------------------------------------- benchmark: 162 tests ----------------------------------------------------------------------------------------------------------------                                        
Name (time in us)                                                                 Min                   Max               Mean             StdDev             Median               IQR            Outliers  OPS (Kops/s)            Rounds  Iterations                                        
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                        
test_ast_generation_on_source_files[pass]                                      5.1670 (1.0)         17.7540 (1.08)      5.4733 (1.0)       0.3186 (1.28)      5.4240 (1.0)      0.0850 (1.18)    2392;4010      182.7035 (1.0)       55442           1                                        
test_ast_generation_on_source_files[import]                                    5.6210 (1.09)        16.4560 (1.0)       5.9020 (1.08)      0.4502 (1.81)      5.8110 (1.07)     0.0780 (1.08)    1668;1970      169.4351 (0.93)      38247           1                                        
test_ast_generation_on_source_files[global]                                    5.7380 (1.11)        17.7370 (1.08)      6.1331 (1.12)      0.5458 (2.19)      6.0140 (1.11)     0.1110 (1.54)    2535;2695      163.0508 (0.89)      48636           1                                        
```

I find that unexpected. Can you reproduce this behaviour?

**Comment by lysnikolaou** [comment]
Yes, with even more extreme deviations.

```
---------------------------------------------------------------------------------------------------------------- benchmark: 162 tests ----------------------------------------------------------------------------------------------------------------
Name (time in us)                                                                 Min                   Max               Mean             StdDev             Median               IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_ast_generation_on_source_files[pass]                                      5.9650 (1.0)        102.9840 (3.98)      6.3927 (1.0)       1.7391 (2.14)      6.2050 (1.0)      0.0990 (1.09)    1263;2511      156.4284 (1.0)       49542           1
test_ast_generation_on_source_files[import]                                    6.5370 (1.10)        83.4210 (3.22)      6.9902 (1.09)      1.2459 (1.53)      6.8820 (1.11)     0.1000 (1.10)     838;1660      143.0578 (0.91)      43515           1
test_ast_generation_on_source_files[return]                                    6.7440 (1.13)       442.2100 (17.08)     7.4519 (1.17)      4.7127 (5.79)      7.0730 (1.14)     0.1110 (1.22)     470;3341      134.1932 (0.86)      44997           1
```

**Comment by gvanrossum** [comment]
I don't understand the output. What do Min and Max represent? Why is Max orders of magnitude larger than Min? Maybe we're better off writing our own benchmarking code so we actually know what we're measuring?

Separately, benchmarking tests is usually not a great idea, since the tests execute atypical code. We should benchmark something like `make simpy`.

**Comment by lysnikolaou** [comment]
> I don't understand the output. What do Min and Max represent? Why is Max orders of magnitude larger than Min? Maybe we're better off writing our own benchmarking code so we actually know what we're measuring?
> 
> Separately, benchmarking tests is usually not a great idea, since the tests execute atypical code. We should benchmark something like `make simpy`.

OK! We can close this then.

**Pull request closed without merging**
