### PR TITLE
WIP: simpy_cpython runtime logs

### PR DESCRIPTION
**Pull request by lysnikolaou**
I'm opening this WIP PR for the log file with the results of the timings, so that we have a picture until we set up something like `asv`.

### CODE REVIEW

**Comment by lysnikolaou** [comment]
Note, that this has `GitPython` as a dependency, which is not listed in `requirements.pip`. 

I can work on doing the necessary changes, in case we want to merge in the script.

**Comment by gvanrossum** [comment]
Thanks! One insight from this is that there's a lot of noise in these numbers. But apart from that, the biggest jump seems to be for 9cda37b0e24a24285cdb5ab6902a1b187391a5a1. I think the biggest change in that commit is that it generates an AST for `primary`, which probably makes the AST much bigger, since so many nodes are created that weren't before, for `Attribute`, `Subscript` and `Call` (which are of course very common). As an experiment I went into that commit and removed the actions for all of `primary`'s alternatives, and most of the speed was given back.

Part of this is AST *construction* (allocating and filling more nodes), but I bet that the bulk of it is *translating* the internal representation of AST nodes to the Python-usable AST nodes (`ast.AST`). This is done by calling `PyAST_mod2obj(res)` in `run_parser()` in `pegen/pegen.c`. This translation process is not free, but we don't care for it from the POV of speeding up the parser, since in *normal* use we skip that translation in favor of compiling to bytecode.

Perhaps we can repeat the experiment with a patch that uses the `mode` flag to suppress the AST translation. (In which case `parse_string()` and `parse_file()` will always return `None`.) Maybe the easiest hack is to remove the type from `start[mod_ty]`.

**Comment by gvanrossum** [comment]
Yeah, a simple test suggests that the cost of `PyAST_mod2obj()` is an order of magnitude more than the cost of constructing the AST nodes for `primary`.

**Comment by lysnikolaou** [comment]
How were the preliminary results mentioned in the README generated? Was it `simpy_cpython` or something else?

**Comment by gvanrossum** [comment]
As the text mentions it was parsing data:xxl.txt.

**Comment by lysnikolaou** [comment]
Yeah, sorry. Didn't make myself clear at all. Were you using some kind of script that would parse data/xxl.txt a few times and would compute the mean or were you parsing it just once?

My point is, if there is such a script, it would be really interesting to run it again and see what the difference in speed is.

**Comment by gvanrossum** [comment]
I don’t recall automating that, sorry.

**Comment by gvanrossum** [comment]
Well, there's `test/timings.py`, although it seems to need a lot of help.
```
python3 -m pegen -c data/simpy.gram --compile
PYTHONPATH=. python3 test/timings.py data/xxl.txt
```

**Pull request closed without merging**
