### PR TITLE
Format pegen.c according to PEP7

### PR DESCRIPTION
**Pull request by pablogsal**
Done with a combination of:

```
clang-tidy pegen/pegen.c -fix -checks="readability-braces-around-statements" -- COMPILE_OPTIONS
```

and this `clang-format pegen/pegen.c` with this `.clang-format` config file:

```
# A clang-format style that approximates Python's PEP 7
BasedOnStyle: Google
AlwaysBreakAfterReturnType: All
AllowShortIfStatementsOnASingleLine: false
AlignAfterOpenBracket: Align
BreakBeforeBraces: Stroustrup
ColumnLimit: 95
DerivePointerAlignment: false
IndentWidth: 4
Language: Cpp
PointerAlignment: Right
ReflowComments: true
SpaceBeforeParens: ControlStatements
SpacesInParentheses: false
TabWidth: 4
UseTab: Never
```

Tell me if you wish me to commit those files and maybe add a new makefile target.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Maybe wait until #169 has landed?

**Comment by gvanrossum** [comment]
Or maybe just land, since #169 needs to be redone. Lysandros?

**Comment by lysnikolaou** [comment]
> Or maybe just land, since #169 needs to be redone. Lysandros?

Yeah, let's land this and I'll merge master before I redo #169.

**Comment by lysnikolaou** [comment]
@pablogsal I like the idea of having a Makefile target for this, like we do with black. Could you do it?

**Comment by pablogsal** [comment]
> @pablogsal I like the idea of having a Makefile target for this, like we do with `black`. Could you do it?

Yeah, I will make a PR soon :)

**Pull request merged**
