### PR TITLE
Implement @ notation to include headers

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Can you do a separate PR first that renames `Rules` to `Grammar`?

**Comment by pablogsal** [comment]
> Can you do a separate PR first that renames `Rules` to `Grammar`?

Yes, I am currently working on that. Then I will fix the errors in the CI

**Comment by pablogsal** [comment]
Rebased on top of #39

**Comment by pablogsal** [comment]
Rebased on master after merging #40

**Pull request merged**
