### PR TITLE
Typo fix in pegen.c

### PR DESCRIPTION
**Pull request by lysnikolaou**

### CODE REVIEW

**Comment by lysnikolaou** [comment]
@gvanrossum I can't merge this due to Travis failing, so could you do it?

**Comment by pablogsal** [comment]
Thanks for the catch and the fix, @lysnikolaou!

I am a bit surprised Travis didn't catch this (In https://travis-ci.com/gvanrossum/pegen/jobs/274043173 the only failing test is the generator expression one).

Should we explore adding a debug target to Travis that triggers the asserts?

**Comment by lysnikolaou** [comment]
@pablogsal How would we do that? Do we need to change something in our Travis configuration?

**Comment by pablogsal** [comment]
> @pablogsal How would we do that? Do we need to change something in our Travis configuration?

Opened https://github.com/gvanrossum/pegen/pull/143 for that :)

**Pull request merged**
